<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="InterfacesServicios\" />
      <Folder Include="Servicios\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WinniElectricidad.AccesoDatos\WinniElectricidad.AccesoDatos.csproj" />
      <ProjectReference Include="..\WinniElectricidad.Compartido\WinniElectricidad.Compartido.csproj" />
    </ItemGroup>

</Project>
