<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WinniElectricidad.AccesoDatos\WinniElectricidad.AccesoDatos.csproj" />
      <ProjectReference Include="..\WinniElectricidad.Compartido\WinniElectricidad.Compartido.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Resend" Version="0.1.7" />
    </ItemGroup>

</Project>
