// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinniElectricidad.AccesoDatos.Repositorios.EF;

#nullable disable

namespace WinniElectricidad.AccesoDatos.Migrations
{
    [DbContext(typeof(WinniElectricidadContext))]
    [Migration("20260127235922_MigracionMercadoPagoHook")]
    partial class MigracionMercadoPagoHook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservaServicio", b =>
                {
                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdReserva", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("ReservaServicio", (string)null);
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Apto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Esquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int?>("UsuarioAdministradorIdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioBaseIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("UsuarioAdministradorIdUsuario");

                    b.HasIndex("UsuarioBaseIdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.OneTimeToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEl")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiraEl")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("IdUsuario", "Tipo", "Usado", "ExpiraEl");

                    b.ToTable("OneTimeTokens", (string)null);
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("EstadoPago")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraRealizado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<long?>("MercadoPagoPaymentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPresupuesto")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UsuarioClienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdReserva")
                        .IsUnique();

                    b.HasIndex("UsuarioClienteIdUsuario");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoReserva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCliente")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereConfirmacionCliente")
                        .HasColumnType("bit");

                    b.Property<int>("TipoServicioReserva")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("FechaReserva")
                        .IsUnique()
                        .HasFilter("[EstadoReserva] <> 2");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntajeReseniaIa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Resenias");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Otro");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Instalaciones, reparaciones y mantenimiento eléctrico en hogares y comercios.",
                            Icono = "Electricidad",
                            Titulo = "Electricidad"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Instalación y reparación de cañerías, griferías y artefactos sanitarios.",
                            Icono = "Sanitaria",
                            Titulo = "Sanitaria"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Instalación y mantenimiento de sistemas de aire acondicionado y calefacción.",
                            Icono = "Climatización",
                            Titulo = "Climatización"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Instalación y mantenimiento de sistemas de riego para jardines.",
                            Icono = "Riego",
                            Titulo = "Riego"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Servicios técnicos generales sujetos a evaluación previa.",
                            Icono = "Otro",
                            Titulo = "Otro"
                        });
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.ServicioImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.ToTable("ServicioImagenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsPrincipal = true,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad.jpg"
                        },
                        new
                        {
                            Id = 2,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            EsPrincipal = false,
                            ServicioId = 1,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/electricidad8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            EsPrincipal = true,
                            ServicioId = 2,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/sanitaria.jpg"
                        },
                        new
                        {
                            Id = 10,
                            EsPrincipal = false,
                            ServicioId = 2,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/sanitaria2.jpg"
                        },
                        new
                        {
                            Id = 11,
                            EsPrincipal = false,
                            ServicioId = 2,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/sanitaria3.jpg"
                        },
                        new
                        {
                            Id = 12,
                            EsPrincipal = false,
                            ServicioId = 2,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/sanitaria4.jpg"
                        },
                        new
                        {
                            Id = 13,
                            EsPrincipal = false,
                            ServicioId = 2,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/sanitaria5.jpg"
                        },
                        new
                        {
                            Id = 14,
                            EsPrincipal = true,
                            ServicioId = 3,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/climatizacion.jpg"
                        },
                        new
                        {
                            Id = 15,
                            EsPrincipal = false,
                            ServicioId = 3,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/climatizacion2.jpg"
                        },
                        new
                        {
                            Id = 16,
                            EsPrincipal = false,
                            ServicioId = 3,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/climatizacion3.jpg"
                        },
                        new
                        {
                            Id = 17,
                            EsPrincipal = true,
                            ServicioId = 4,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/riego.jpg"
                        },
                        new
                        {
                            Id = 18,
                            EsPrincipal = false,
                            ServicioId = 4,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/riego2.jpg"
                        },
                        new
                        {
                            Id = 19,
                            EsPrincipal = true,
                            ServicioId = 5,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/otros.jpg"
                        },
                        new
                        {
                            Id = 20,
                            EsPrincipal = false,
                            ServicioId = 5,
                            Url = "https://winnielectricidadstorage.blob.core.windows.net/imagenes/servicios/otros2.jpg"
                        });
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasMaximos")
                        .HasColumnType("int");

                    b.Property<int>("DiasMinimos")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("MinutosEntreTurnos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiasMaximos = 30,
                            DiasMinimos = 2,
                            HoraFin = new TimeOnly(17, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0),
                            MinutosEntreTurnos = 90
                        });
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UsuarioBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioAdministrador", b =>
                {
                    b.HasBaseType("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase");

                    b.HasDiscriminator().HasValue("UsuarioAdministrador");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", b =>
                {
                    b.HasBaseType("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase");

                    b.HasDiscriminator().HasValue("UsuarioCliente");
                });

            modelBuilder.Entity("ReservaServicio", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Reserva", null)
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Servicio", null)
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Direccion", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", "UsuarioCliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCliente");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioAdministrador", null)
                        .WithMany("NotificacionesEnviadas")
                        .HasForeignKey("UsuarioAdministradorIdUsuario");

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", null)
                        .WithMany("NotificacionesRecibidas")
                        .HasForeignKey("UsuarioBaseIdUsuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.OneTimeToken", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Presupuesto", "Presupuesto")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presupuesto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Presupuesto", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Reserva", "Reserva")
                        .WithOne("Presupuesto")
                        .HasForeignKey("WinniElectricidad.LogicaNegocio.Entidades.Presupuesto", "IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", null)
                        .WithMany("Presupuestos")
                        .HasForeignKey("UsuarioClienteIdUsuario");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reserva", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("IdDireccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", "UsuarioCliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("UsuarioCliente");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reseña", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Servicio", null)
                        .WithMany("Reseñas")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", null)
                        .WithMany("Reseñas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.ServicioImagen", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.Servicio", "Servicio")
                        .WithMany("Imagenes")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Presupuesto", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reserva", b =>
                {
                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Servicio", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", b =>
                {
                    b.Navigation("NotificacionesRecibidas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioAdministrador", b =>
                {
                    b.Navigation("NotificacionesEnviadas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pagos");

                    b.Navigation("Presupuestos");

                    b.Navigation("Reservas");

                    b.Navigation("Reseñas");
                });
#pragma warning restore 612, 618
        }
    }
}
