// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinniElectricidad.AccesoDatos.Repositorios.EF;

#nullable disable

namespace WinniElectricidad.AccesoDatos.Migrations
{
    [DbContext(typeof(WinniElectricidadContext))]
    partial class WinniElectricidadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Apto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Esquina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioClienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdDireccion");

                    b.HasIndex("UsuarioClienteIdUsuario");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<int?>("UsuarioBaseIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("UsuarioBaseIdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPago");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<int?>("UsuarioClienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("UsuarioClienteIdUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UsuarioBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", b =>
                {
                    b.HasBaseType("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase");

                    b.HasDiscriminator().HasValue("UsuarioCliente");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Direccion", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioClienteIdUsuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Notificacion", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", null)
                        .WithMany("NotificacionesRecibidas")
                        .HasForeignKey("UsuarioBaseIdUsuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Pago", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.Reserva", b =>
                {
                    b.HasOne("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioClienteIdUsuario");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioBase", b =>
                {
                    b.Navigation("NotificacionesRecibidas");
                });

            modelBuilder.Entity("WinniElectricidad.LogicaNegocio.Entidades.UsuarioCliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pagos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
