name: Runs tests

on:
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          echo "No projects yet — skipping restore for now. Then: dotnet restore"

      - name: SonarCloud Begin Analysis
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"winnielectricidad" /o:"winnielectricidad" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  
      - name: Build project
        run: |
          echo "No projects yet — skipping build execution. Then: dotnet build --no-restore --configuration Release"

      - name: Run tests
        run: |
          echo "No test projects yet — skipping test execution. Then: dotnet test --no-build --configuration Release --verbosity normal"

      - name: SonarCloud End Analysis
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"