name: Runs tests

on:
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:
    
permissions:
  contents: read
  checks: write
  pull-requests: write    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./WinniElectricidad-Backend
        continue-on-error: true

      - name: SonarCloud Begin Analysis
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"winnielectricidad" /o:"winnielectricidad" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.pullrequest.provider=GitHub \
            /d:sonar.pullrequest.github.repository=${{ github.repository }} \
            /d:sonar.pullrequest.key=${{ github.event.pull_request.number }} \
            /d:sonar.pullrequest.branch=${{ github.head_ref }} \
            /d:sonar.pullrequest.base=develop \
            /d:sonar.cs.vstest.reportsPaths=**/TestResults/*.trx \
            /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml \
            /d:sonar.coverage.exclusions=**/Migrations/**,**/*.Tests*/**,**/Program.cs \
            /d:sonar.qualitygate.wait=true
        working-directory: ./WinniElectricidad-Backend
  
      - name: Build project
        run: dotnet build --no-restore --configuration Release
        working-directory: ./WinniElectricidad-Backend
        continue-on-error: true

      - name: Run tests
        run: |
          dotnet test --no-build --configuration Release \
          --logger 'trx;LogFileName=test_results.trx' \
          /p:CollectCoverage=true \
          /p:CoverletOutput=./TestResults/coverage.opencover.xml \
          /p:CoverletOutputFormat=opencover
        working-directory: ./WinniElectricidad-Backend
        continue-on-error: true
          
      - name: Publish test results
        if: ${{ always() }}
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: './WinniElectricidad-Backend/**/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false                       
          
      - name: SonarCloud End Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        working-directory: ./WinniElectricidad-Backend
        continue-on-error: true