name: SonarCloud Init (Develop)

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  sonarcloud-init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Analysis (Develop)
        run: |
          dotnet sonarscanner begin \
            /k:"winnielectricidad" \
            /o:"winnielectricidad" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vstest.reportsPaths=WinniElectricidad-Backend/**/TestResults/*.trx \
            /d:sonar.cs.opencover.reportsPaths=WinniElectricidad-Backend/**/coverage.cobertura.xml \
            /d:sonar.coverage.exclusions=**/Migrations/**,**/*.Tests/** \
            /d:sonar.qualitygate.wait=true

          dotnet build ./WinniElectricidad-Backend --configuration Release

          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
